name       : llvm-roc
version    : 3.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/llvm-project/archive/roc-ocl-3.1.0.tar.gz : fb62584b8db54483e40e3c6ec35da700455b7e9bce5ce152a1382243a064c387
homepage   : https://github.com/RadeonOpenCompute/llvm-project
license    : Apache-2.0-with-LLVM-exception
component  : programming.devel
summary    : ROCm llvm component
description: |
    The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. Despite its name, LLVM has little to do with traditional virtual machines. The name "LLVM" itself is not an acronym; it is the full name of the project.
clang      : yes
setup      : |
    cd llvm
    %cmake_ninja \
        -DCMAKE_INSTALL_PREFIX="%libdir%/llvm/roc" \
        -DLLVM_BUILD_DOCS=NO \
        -DLLVM_ENABLE_DOXYGEN=OFF \
        -DLLVM_ENABLE_OCAMLDOC=OFF \
        -DLLVM_ENABLE_PROJECTS="clang;lld" \
        -DLLVM_ENABLE_SPHINX=NO \
        -DLLVM_INSTALL_UTILS=ON \
        -DLLVM_TARGETS_TO_BUILD="AMDGPU;X86" \
        -DLLVM_USE_LINKER=lld \
        -DLLVM_VERSION_SUFFIX=roc \
        -DOCAMLFIND=NO .
build      : |
    cd llvm
    %ninja_build -j4
install    : |
    cd llvm
    %ninja_install
